### ISSUE TITLE
Battery status not working

### ISSUE THREAD

**Issue by AdhamAlbanna** [Flashminat0/hp-probook-450-g5-big-sur-opencore-efi-files#4]
Thank you very much for this wonderful work
And please fix the battery status and the trackpad gestures
I'm waiting for new release🙏🏻🙏🏻

**Comment by Flashminat0** [comment]
I'm not using the laptop anymore it was my old one. trackpad can be fixed using some kext changes and such , but battery cant i tried to fix it and wifi didnt work. so better wifi than battery
